using System.Runtime.CompilerServices;

// The tests exercise the internal view models and presentation helpers. The
// version is generated by the SDK and must not be hand-written here; see the Abstractions
// AssemblyInfo for why.
[assembly: InternalsVisibleTo("Dongled.App.Tests")]
